training_data: data/alpaca_eval_train.json
test_data: data/alpaca_eval_test.json
continue_from:
  step: annotation
  exp_dir: exp/saved_outputs/alpaca_eval/gpt4o/icai
  reannotate_invalid: true
  copy_files: false

annotation:
  model: openrouter/openai/gpt-4o
  num_votes_per_annotation: 1
  use_all_annotators_if_none_selected: true
  conflict_strategy: unanimous

constitutional_annotator:
  method: flat
  flat_annotator:
    aggregation: llm
    model: openrouter/openai/gpt-4o
    selection:
      max_principles: 30
      require_max_principles: true
      order_by: majority_perf
      filter_min_relevance: 0.01

plotting:
  generate: false
