training_data: data/alpaca_eval_train.json
test_data: data/alpaca_eval_test.json
continue_from:
  step: annotation
  exp_dir: exp/saved_outputs/alpaca_eval/deepseek/icai_plus
  copy_files: false

annotation:
  model: null
  num_votes_per_annotation: 1
  conflict_strategy: unanimous

constitutional_annotator:
  method: flat
  flat_annotator:
    aggregation: priority
    selection:
      max_principles: 30
      require_max_principles: true
      order_by: majority_perf

plotting:
  generate: false
