training_data: data/alpaca_eval_train.json
test_data: data/alpaca_eval_test.json
continue_from:
  step: annotation
  exp_dir: exp/saved_outputs/alpaca_eval/gpt5.4-nano/icai_plus
  copy_files: false

annotation:
  model: null
  num_votes_per_annotation: 1
  conflict_strategy: unanimous

constitutional_annotator:
  method: tree
  tree_annotator:
    type: DecisionTree
    tuning:
      enabled: true

plotting:
  generate: false
