training_data: data/processed/misc/arena2025_arena-human-preference-140k_5000chars_english_no-sep-prompt_800samples_train_ap.json
test_data: data/processed/misc/arena2025_arena-human-preference-140k_5000chars_english_no-sep-prompt_400samples_test_ap.json
discovery:
  model: openrouter/openai/gpt-4o
annotation:
  model: openrouter/openai/gpt-4o
classic_icai:
  run: true
  internal_config:
    alg_model: openrouter/openai/gpt-4o
    alg_model_cache: true
    alg_use_openrouter: true
    test_data_annotate_with_principles: true
    #generate_constitution: true
    #s0_added_principles_to_test: null
    #s0_added_standard_principles_to_test: null
    #s0_skip_principle_generation: false
    s1_num_samples_for_principle_generation: 100
    s1_num_principles_per_sampling_step: 4
    #s1_num_principles_per_instance: null
    #s1_num_rankings_per_sampling_step: 1
    s2_num_clusters: 100
    #s2_random_clusters: false
    #s2_sample_cluster_instead_of_rewrite: true
    #s3_skip_voting_entirely: false
    s3_filter_max_votes_in_single_prompt: 10
    s3_num_seeds_to_reannotate_with: 1
    #s3_voting_method_cross_seed: unanimous
    #s3_voting_max_output_tokens: 3000
    #s3_filter_majority_true: true
    #s3_filter_majority_relevant: false
    #s3_filter_majority_valid: true
    s3_filter_min_relevance: 0.05
    #s3_order_by: for_minus_against
    s3_max_principles: 30
    #s3_ratio_of_max_principles_to_cluster_again: 1.5
    s3_skip_prompt_principle_generation: true
    annotator:
      alpaca_eval:
        skip: false
#        create_other_annotator_tmp_configs: true
#        constitution: null
#        is_single_annotator: true
        base_constitutional_annotator_configs:
        - gpt4o_fn_constitutional_base_neutral_v2
        other_annotator_configs: []
#      fn_annotators: []
#      skip: false
#      test_data_only: false
#      create_other_annotator_tmp_configs: true
#      constitution: null
#      is_single_annotator: false
#      base_constitutional_annotator_configs: []
#      other_annotator_configs: []
    alg_prompts:
      generator_prompts:
      - |-
        <|im_start|>system
        Your job is to analyse data and come up with explanations. You're an expert at this.
        <|im_end|>
        <|im_start|>user
        Selected sample:
        {preferred_sample}

        Other sample:
        {rejected_sample}

        Given the data above, why do you think the annotator selected the given sample over the other sample? Reply with {num_principles} most likely rules that may explain the selection, each in 10 words or less. Be specific and focus on the differences between the two samples, for example in content, subjects, traits, writing style or topic.  Always suggest as rule that starts with 'Select the response that...'.

        Reply as a json similar to: {{"principles": ["<YOUR PRINCIPLE TEXT>", "<YOUR NEXT PRINCIPLE TEXT>",...]}}.
        DO NOT respond with any text apart from the json format above!
        DO NOT add markdown formatting around JSON.
        ONLY REPLY IN JSON FORMAT
        <|im_end|>

      voting_prompt: |-
        <|im_start|>system
        Your job is to check which sample is should be selected according to the given rules. You're an expert at this.
        <|im_end|>
        <|im_start|>user
        Sample A:
        {sample_a}

        Sample B:
        {sample_b}

        Given the samples data above, check for each rule below which sample should be selected:
        {summaries}

        Answer in json format, e.g. {{0: "A", 1: "B", 2: "None",...}}.
        Put "A" if A is selected according to that rule, and "B" if B is selected. Put "None" if a rule is not applicable to the two samples.
        No ties are allowed, only one of "A", "B" or "None".
        Vote for all rules, even if you are unsure.
        DO NOT respond with any text apart from the json format above!
        DO NOT add markdown formatting around JSON.
        ONLY REPLY IN JSON FORMAT
        <|im_end|>

      cluster_summary_prompt: |-
        <|im_start|>system
        Your job is to summarize the principles below as a single similar principle. Ignore outlier principles. The principle should be an instruction about choosing one of the options.
        <|im_end|>
        <|im_start|>user
        {principles}
        <|im_end|>
