training_data: data/alpaca_eval_train.json
test_data: data/alpaca_eval_test.json
continue_from:
  step: blended_discovery
  blend:
    sources:
      - exp/saved_outputs/alpaca_eval/gpt4o/icai_plus
    select:
      order_by: random
      max_principles: 10

annotation:
  - model: openrouter/openai/gpt-4o
    batch_size: 10
    num_votes_per_annotation: 2

constitutional_annotator:
  method: dummy
