training_data: data/processed/misc/prism_800samples_train_ap.json
test_data: data/processed/misc/prism_400samples_test_ap.json
continue_from:
  step: annotation
  exp_dir: exp/saved_outputs/prism/gpt4o-mini/icai
  reannotate_invalid: true
  copy_files: false

annotation:
  use_all_annotators_if_none_selected: true
  model: openrouter/openai/gpt-4o-mini-2024-07-18
  num_votes_per_annotation: 1
  use_all_annotators_if_none_selected: true
  conflict_strategy: unanimous

constitutional_annotator:
  method: tree
  tree_annotator:
    type: LightGBM
    tuning:
      enabled: true
      n_trials: 40

plotting:
  generate: false
